package com.example.demo;

// Generated by Selenium IDE
// import java.util.HashMap;
// import java.util.Map;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class ToTicketTest {
  private WebDriver driver;
  //private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void toTicket() {
    driver.get("http://www.hnmsg.net/");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver
      .findElement(
        By.cssSelector(".fl:nth-child(1) > .sHoverItem:nth-child(1) .fsize20")
      )
      .click();
    driver.findElement(By.linkText("个人预约")).click();
    driver.findElement(By.id("userPhone")).click();
    driver.findElement(By.id("userPhone")).sendKeys("13874995433");
    driver.findElement(By.name("userName")).click();
    driver.findElement(By.name("userName")).sendKeys("陈昊");
    driver.findElement(By.id("certificateNum")).click();
    driver.findElement(By.id("certificateNum")).sendKeys("431081198809095119");
    driver.findElement(By.id("sendForm")).click();
    driver.findElement(By.cssSelector(".ticketBox")).click();
    driver.findElement(By.linkText("查看订单")).click();
  }
}
